name: Make Clean Branch

on:
  push:
    branches:
      - main

jobs:
  clean-branch:
    name: update clean branch
    runs-on: arc-runner-set
    container:
      image: asia-northeast3-docker.pkg.dev/manythings-mitosis/docker-images/arc-runner-alpine
      credentials:
        username: _json_key
        password: ${{ secrets.GOOGLE_CREDENTIAL }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: clean

      - name: run update
        run: |
          git fetch
          git checkout origin/main src
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "cleaned $GITHUB_SHA"
          git push
